import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Card API - Complete guide for trading cards
  cardApiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'card-api',
    },
  ],

  // Infrastructure - Deployment, Azure, CI/CD
  infrastructureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'infrastructure',
    },
  ],
};

export default sidebars;
