import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Getting Started - Quickstart guides and authentication
  gettingStartedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'getting-started',
    },
  ],

  // API Reference - Core API, Assistant API, Pilot API
  apiReferenceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],

  // Guides - Point System, Market Analysis, Trading Strategies
  guidesSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],

  // Infrastructure - Deployment, Azure, CI/CD
  infrastructureSidebar: [
    {
      type: 'autogenerated',
      dirName: 'infrastructure',
    },
  ],
};

export default sidebars;
